# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20170906_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.item')),
            ],
        ),
    ]
