# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20171001_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
