# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_item_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
