# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.RemoveField(
            model_name='item',
            name='in_cart',
        ),
    ]
